<?php

declare(strict_types=1);

namespace BlueprintAU\Radiant\Database\Schema\Grammars;

use BlueprintAU\Radiant\Database\Schema\Blueprint;
use BlueprintAU\Radiant\Database\Schema\Enums\ColumnType;
use BlueprintAU\Radiant\Database\Schema\Enums\SchemaOperation;

/**
 * The Postgres dialect of the schema grammar.
 *
 * Identifiers are quoted with double quotes (embedded quotes doubled).
 * Auto-increment renders as `GENERATED BY DEFAULT AS IDENTITY` (the modern
 * SQL-standard identity column, preferred over `SERIAL`). Postgres supports
 * dropping columns natively.
 */
class PostgresSchemaGrammar extends SchemaGrammar
{
    /**
     * Wrap an identifier in Postgres double quotes.
     *
     * @param string $value The identifier to quote.
     * @return string The quoted identifier.
     */
    protected function wrap(string $value): string
    {
        return '"' . str_replace('"', '""', $value) . '"';
    }

    /**
     * Map a logical column type to Postgres' native type.
     *
     * @param ColumnType $type The logical column type.
     * @param int|null $length The column length, if any.
     * @return string The Postgres type.
     */
    protected function type(ColumnType $type, ?int $length = null): string
    {
        return match ($type) {
            ColumnType::String => 'varchar(' . $this->requireLength($length) . ')',
            ColumnType::BigInt => 'bigint',
            ColumnType::Int => 'integer',
            ColumnType::Float => 'double precision',
            ColumnType::Boolean => 'boolean',
            ColumnType::DateTime => 'timestamp',
            ColumnType::Timestamp => 'timestamp',
            ColumnType::Json => 'jsonb',
        };
    }

    /**
     * The Postgres auto-increment clause.
     *
     * @return string The clause.
     */
    protected function autoIncrement(): string
    {
        return 'GENERATED BY DEFAULT AS IDENTITY';
    }

    /**
     * Compile an `ALTER TABLE ... DROP COLUMN` statement.
     *
     * @param string $table The table name.
     * @param Blueprint $blueprint The columns to drop.
     * @return string The compiled SQL.
     */
    protected function compileDropColumn(string $table, Blueprint $blueprint): string
    {
        $columns = $blueprint->getDropColumns();
        if ($columns === []) {
            throw new \InvalidArgumentException('Cannot drop columns with no columns defined.');
        }

        return 'ALTER TABLE ' . $this->wrap($table) . ' DROP COLUMN ' . implode(', DROP COLUMN ', array_map(
            fn (string $column) => $this->wrap($column),
            $columns,
        ));
    }
}