<?php

declare(strict_types=1);

namespace BlueprintAU\Radiant\Database\Schema\Grammars;

use BlueprintAU\Radiant\Database\Schema\Blueprint;
use BlueprintAU\Radiant\Database\Schema\Enums\ColumnType;

/**
 * The Postgres dialect of the schema grammar.
 *
 * Identifiers are quoted with double quotes (embedded quotes doubled).
 * Auto-increment renders as `GENERATED BY DEFAULT AS IDENTITY` (the modern
 * SQL-standard identity column, preferred over `SERIAL`). Postgres supports
 * dropping columns natively.
 */
class PostgresSchemaGrammar extends SchemaGrammar
{
    /**
     * Wrap an identifier in Postgres double quotes.
     *
     * @param string $value The identifier to quote.
     * @return string The quoted identifier.
     */
    protected function wrap(string $value): string
    {
        return '"' . str_replace('"', '""', $value) . '"';
    }

    /**
     * Map a logical column type to Postgres' native type.
     *
     * @param ColumnType $type The logical column type.
     * @param int|null $length The column length, if any.
     * @return string The Postgres type.
     */
    protected function type(ColumnType $type, ?int $length = null): string
    {
        return match ($type) {
            ColumnType::String => 'varchar(' . $this->requireLength($length) . ')',
            ColumnType::BigInt => 'bigint',
            ColumnType::Int => 'integer',
            ColumnType::Float => 'double precision',
            ColumnType::Boolean => 'boolean',
            ColumnType::DateTime => 'timestamp',
            ColumnType::Timestamp => 'timestamp',
            ColumnType::Json => 'jsonb',
        };
    }

    /**
     * The Postgres auto-increment clause.
     *
     * @return string The clause.
     */
    protected function autoIncrement(): string
    {
        return 'GENERATED BY DEFAULT AS IDENTITY';
    }

    /**
     * Postgres 15+ renders the NULLS clause EXPLICITLY in both directions:
     * `NULLS DISTINCT` pins the SQL default (multiple NULLs allowed) in
     * the DDL, `NULLS NOT DISTINCT` upgrades to at-most-one-NULL semantics.
     *
     * @param bool $nullsNotDistinct The declared option value.
     * @return string The clause text.
     */
    protected function compileNullsNotDistinctClause(bool $nullsNotDistinct): string
    {
        return $nullsNotDistinct ? 'NULLS NOT DISTINCT' : 'NULLS DISTINCT';
    }

    /**
     * Postgres renders partial (filtered) indexes — `CREATE INDEX ... WHERE
     * predicate`.
     *
     * @param string $predicate The declared predicate, spliced verbatim.
     * @return string The clause text.
     */
    protected function compilePartialIndexClause(string $predicate): string
    {
        return 'WHERE ' . $predicate;
    }

    /**
     * Postgres renders `DEFERRABLE [INITIALLY DEFERRED]` on foreign keys —
     * the option circular-FK seeding within one transaction depends on.
     *
     * @param bool $initiallyDeferred Whether the constraint starts
     *        INITIALLY DEFERRED.
     * @return string The clause text.
     */
    protected function compileDeferrableClause(bool $initiallyDeferred): string
    {
        return $initiallyDeferred ? 'DEFERRABLE INITIALLY DEFERRED' : 'DEFERRABLE';
    }

    /**
     * Postgres drops an index by name alone: `DROP INDEX name`.
     *
     * @param string $name The index name.
     * @param string $table The table the index is on (unused — Postgres
     *        indexes live in their own namespace).
     * @return string The compiled SQL.
     */
    public function compileDropIndex(string $name, string $table): string
    {
        unset($table);
        $this->assertValidIdentifier($name);

        return 'DROP INDEX ' . $this->wrap($name);
    }

    /**
     * Compile an `ALTER TABLE ... DROP COLUMN` statement.
     *
     * @param Blueprint $blueprint The table and columns to drop.
     * @return string The compiled SQL.
     */
    protected function compileDropColumn(Blueprint $blueprint): string
    {
        $table = $blueprint->getTable();
        $columns = $blueprint->getDropColumns();
        if ($columns === []) {
            throw new \InvalidArgumentException('Cannot drop columns with no columns defined.');
        }

        return 'ALTER TABLE ' . $this->wrap($table) . ' DROP COLUMN ' . implode(', DROP COLUMN ', array_map(
            fn (string $column) => $this->wrap($column),
            $columns,
        ));
    }

    /**
     * Postgres caps identifiers at 63 bytes (NAMEDATALEN minus the
     * terminator) — a derived index name over a long table/column set can
     * exceed it. Fail fast at compile time (Doctrine's pattern: the
     * dialect validates, never silently truncates — a truncated name is
     * not stable across syncs and would break the differ).
     *
     * @param string $name The final identifier (index name).
     * @return void
     * @throws \InvalidArgumentException When the identifier exceeds 63 bytes.
     */
    public function assertValidIdentifier(string $name): void
    {
        if (strlen($name) > 63) {
            throw new \InvalidArgumentException(sprintf(
                'Identifier [%s] exceeds Postgres\'s 63-byte limit (%d bytes); '
                . 'declare a shorter #[Unique(name: ...)] / #[Index(name: ...)].',
                $name,
                strlen($name),
            ));
        }
    }
}