<?php

declare(strict_types=1);

namespace BlueprintAU\Radiant\Tests\Unit\Schema;

use BlueprintAU\Radiant\Database\Connections\SqliteConnection;
use BlueprintAU\Radiant\Database\Exceptions\UnsupportedFeatureException;
use BlueprintAU\Radiant\Database\Query\Expression;
use BlueprintAU\Radiant\Database\Schema\Blueprint;
use BlueprintAU\Radiant\Database\Schema\Enums\ColumnType;
use BlueprintAU\Radiant\Database\Schema\Enums\ForeignKeyAction;
use BlueprintAU\Radiant\Database\Schema\Grammars\MySqlSchemaGrammar;
use BlueprintAU\Radiant\Database\Schema\Grammars\PostgresSchemaGrammar;
use BlueprintAU\Radiant\Database\Schema\Grammars\SqliteSchemaGrammar;
use PHPUnit\Framework\TestCase;

/**
 * Compile-only tests for the schema grammar chain, plus a live SQLite
 * round-trip.
 */
final class SchemaGrammarTest extends TestCase
{
    /**
     * A blueprint with a typical users table.
     *
     * @return Blueprint The blueprint.
     */
    private function usersBlueprint(): Blueprint
    {
        return (new Blueprint('users'))
            ->id()
            ->string('name', 255)
            ->column(ColumnType::String, 'email', length: 255, unique: true)
            ->timestamp('email_verified_at')
            ->foreignId('role_id', 'roles.id', onDelete: 'cascade');
    }

    // ---- Create ----

    /**
     * SQLite compiles a CREATE TABLE with quoted identifiers.
     */
    public function testCreateSqlite(): void
    {
        $sql = (new SqliteSchemaGrammar())->compileCreate($this->usersBlueprint());
        self::assertSame(
            'CREATE TABLE "users" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, '
            . '"name" varchar(255) NOT NULL, "email" varchar(255) NOT NULL UNIQUE, '
            . '"email_verified_at" datetime, "role_id" integer NOT NULL, '
            . 'FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON DELETE CASCADE)',
            $sql,
        );
    }

    /**
     * MySQL compiles a CREATE TABLE with backtick quoting and AUTO_INCREMENT.
     */
    public function testCreateMySql(): void
    {
        $sql = (new MySqlSchemaGrammar())->compileCreate($this->usersBlueprint());
        self::assertSame(
            'CREATE TABLE `users` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, '
            . '`name` varchar(255) NOT NULL, `email` varchar(255) NOT NULL UNIQUE, '
            . '`email_verified_at` datetime, `role_id` bigint NOT NULL, '
            . 'FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE)',
            $sql,
        );
    }

    /**
     * Postgres compiles a CREATE TABLE with double-quote quoting and an
     * identity column.
     */
    public function testCreatePostgres(): void
    {
        $sql = (new PostgresSchemaGrammar())->compileCreate($this->usersBlueprint());
        self::assertSame(
            'CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, '
            . '"name" varchar(255) NOT NULL, "email" varchar(255) NOT NULL UNIQUE, '
            . '"email_verified_at" timestamp, "role_id" bigint NOT NULL, '
            . 'FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON DELETE CASCADE)',
            $sql,
        );
    }

    /**
     * A composite primary key is declared table-level.
     */
    public function testCompositePrimaryKey(): void
    {
        $blueprint = (new Blueprint('user_roles'))
            ->column(ColumnType::BigInt, 'user_id', primaryKey: true)
            ->column(ColumnType::BigInt, 'role_id', primaryKey: true);
        $sql = (new SqliteSchemaGrammar())->compileCreate($blueprint);
        self::assertSame(
            'CREATE TABLE "user_roles" ("user_id" integer NOT NULL, "role_id" integer NOT NULL, '
            . 'PRIMARY KEY ("user_id", "role_id"))',
            $sql,
        );
    }

    /**
     * A default value is quoted as a literal.
     */
    public function testDefaultValue(): void
    {
        $blueprint = (new Blueprint('settings'))->column(ColumnType::Boolean, 'active', default: true);
        $sql = (new SqliteSchemaGrammar())->compileCreate($blueprint);
        self::assertSame(
            'CREATE TABLE "settings" ("active" tinyint(1) NOT NULL DEFAULT 1)',
            $sql,
        );
    }

    /**
     * Creating a table with no columns fails fast.
     */
    public function testCreateNoColumnsThrows(): void
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('no columns');
        (new SqliteSchemaGrammar())->compileCreate(new Blueprint('users'));
    }

    /**
     * A string column requires a length — fail-fast rather than a silent
     * default.
     */
    public function testStringRequiresLength(): void
    {
        // Use the low-level column() so a missing length reaches the
        // runtime validation (string() now requires the length at
        // compile-time).
        $blueprint = (new Blueprint('users'))->column(ColumnType::String, 'name');
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('requires a length');
        (new SqliteSchemaGrammar())->compileCreate($blueprint);
    }

    /**
     * A foreign key with a non-bigint type renders that type.
     */
    public function testForeignIdWithExplicitType(): void
    {
        $blueprint = (new Blueprint('posts'))
            ->id()
            ->foreignId('user_uuid', 'users.uuid', ColumnType::String, length: 36);
        $sql = (new MySqlSchemaGrammar())->compileCreate($blueprint);
        self::assertSame(
            'CREATE TABLE `posts` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, '
            . '`user_uuid` varchar(36) NOT NULL, '
            . 'FOREIGN KEY (`user_uuid`) REFERENCES `users` (`uuid`))',
            $sql,
        );
    }

    /**
     * An indexed column compiles a portable CREATE INDEX statement.
     */
    public function testIndexCompilesCreateIndex(): void
    {
        $blueprint = (new Blueprint('posts'))->column(ColumnType::BigInt, 'user_id', index: true);
        $indexes = (new SqliteSchemaGrammar())->compileIndexes($blueprint);
        self::assertSame(
            ['CREATE INDEX "posts_user_id_index" ON "posts" ("user_id")'],
            $indexes,
        );
    }

    /**
     * A unique column is not duplicated as a plain index (already inline).
     */
    public function testUniqueColumnNotIndexedSeparately(): void
    {
        $blueprint = (new Blueprint('users'))->column(ColumnType::String, 'email', length: 255, unique: true, index: true);
        $indexes = (new MySqlSchemaGrammar())->compileIndexes($blueprint);
        self::assertSame([], $indexes);
    }

    /**
     * A blueprint with no indexed columns compiles no index statements.
     */
    public function testNoIndexesWhenNoneDeclared(): void
    {
        $indexes = (new SqliteSchemaGrammar())->compileIndexes($this->usersBlueprint());
        self::assertSame([], $indexes);
    }

    /**
     * A composite index compiles a multi-column CREATE INDEX.
     */
    public function testCompositeIndex(): void
    {
        // An explicit name IS the whole name — rendered verbatim.
        $blueprint = (new Blueprint('memberships'))
            ->index('team_role', ['team_id', 'role_id']);
        $indexes = (new SqliteSchemaGrammar())->compileIndexes($blueprint);
        self::assertSame(
            ['CREATE INDEX "team_role" ON "memberships" ("team_id", "role_id")'],
            $indexes,
        );
    }

    /**
     * A single-column index() with a custom name compiles.
     */
    public function testSingleColumnIndex(): void
    {
        $blueprint = (new Blueprint('users'))
            ->index('active', ['is_active']);
        $indexes = (new MySqlSchemaGrammar())->compileIndexes($blueprint);
        self::assertSame(
            ['CREATE INDEX `active` ON `users` (`is_active`)'],
            $indexes,
        );
    }

    /**
     * A unique composite index compiles CREATE UNIQUE INDEX.
     */
    public function testUniqueCompositeIndex(): void
    {
        $blueprint = (new Blueprint('memberships'))
            ->index('team_user', ['team_id', 'user_id'], unique: true);
        $indexes = (new MySqlSchemaGrammar())->compileIndexes($blueprint);
        self::assertSame(
            ['CREATE UNIQUE INDEX `team_user` ON `memberships` (`team_id`, `user_id`)'],
            $indexes,
        );
    }

    /**
     * An index requires at least one column.
     */
    public function testIndexRequiresColumns(): void
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('at least one column');
        (new Blueprint('users'))->index('empty', []);
    }

    // ---- Dialect-gated index options ----

    /**
     * Postgres renders the NULLS clause EXPLICITLY on a unique index —
     * `NULLS NOT DISTINCT` when declared, `NULLS DISTINCT` (pinning the
     * SQL default) when not, so the DDL is self-documenting either way.
     */
    public function testNullsNotDistinctPostgres(): void
    {
        $blueprint = (new Blueprint('subscriptions'))
            ->index(null, ['user_id'], unique: true, nullsNotDistinct: true);
        $indexes = (new PostgresSchemaGrammar())->compileIndexes($blueprint);
        self::assertSame(
            ['CREATE UNIQUE INDEX "subscriptions_user_id_unique" ON "subscriptions" ("user_id") NULLS NOT DISTINCT'],
            $indexes,
        );

        // The default direction is pinned explicitly too.
        $default = (new Blueprint('subscriptions'))
            ->index(null, ['user_id'], unique: true);
        self::assertSame(
            ['CREATE UNIQUE INDEX "subscriptions_user_id_unique" ON "subscriptions" ("user_id") NULLS DISTINCT'],
            (new PostgresSchemaGrammar())->compileIndexes($default),
        );
    }

    /**
     * NULLS NOT DISTINCT fails fast on MySQL — the constraint would
     * silently be weaker (NULLS DISTINCT) if rendered without the option.
     */
    public function testNullsNotDistinctMySqlThrows(): void
    {
        $blueprint = (new Blueprint('subscriptions'))
            ->index(null, ['user_id'], unique: true, nullsNotDistinct: true);
        $this->expectException(UnsupportedFeatureException::class);
        $this->expectExceptionMessage('NULLS NOT DISTINCT');
        (new MySqlSchemaGrammar())->compileIndexes($blueprint);
    }

    /**
     * NULLS NOT DISTINCT fails fast on SQLite too.
     */
    public function testNullsNotDistinctSqliteThrows(): void
    {
        $blueprint = (new Blueprint('subscriptions'))
            ->index(null, ['user_id'], unique: true, nullsNotDistinct: true);
        $this->expectException(UnsupportedFeatureException::class);
        $this->expectExceptionMessage('NULLS NOT DISTINCT');
        (new SqliteSchemaGrammar())->compileIndexes($blueprint);
    }

    /**
     * Declaring nullsNotDistinct without unique fails at the blueprint —
     * the option is meaningless on a plain index.
     */
    public function testNullsNotDistinctWithoutUniqueThrows(): void
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('only applies to a UNIQUE index');
        (new Blueprint('users'))->index(null, ['user_id'], nullsNotDistinct: true);
    }

    /**
     * Postgres renders a partial (filtered) index.
     */
    public function testPartialIndexPostgres(): void
    {
        $blueprint = (new Blueprint('invitations'))
            ->index(null, ['email'], unique: true, where: 'accepted_at IS NULL');
        $indexes = (new PostgresSchemaGrammar())->compileIndexes($blueprint);
        self::assertSame(
            ['CREATE UNIQUE INDEX "invitations_email_unique" ON "invitations" ("email") NULLS DISTINCT WHERE accepted_at IS NULL'],
            $indexes,
        );
    }

    /**
     * SQLite renders a partial (filtered) index too.
     */
    public function testPartialIndexSqlite(): void
    {
        $blueprint = (new Blueprint('invitations'))
            ->index(null, ['email'], unique: true, where: 'accepted_at IS NULL');
        $indexes = (new SqliteSchemaGrammar())->compileIndexes($blueprint);
        self::assertSame(
            ['CREATE UNIQUE INDEX "invitations_email_unique" ON "invitations" ("email") WHERE accepted_at IS NULL'],
            $indexes,
        );
    }

    /**
     * MySQL has no partial indexes — fail fast rather than silently
     * indexing rows the predicate was supposed to exclude.
     */
    public function testPartialIndexMySqlThrows(): void
    {
        $blueprint = (new Blueprint('invitations'))
            ->index(null, ['email'], where: 'accepted_at IS NULL');
        $this->expectException(UnsupportedFeatureException::class);
        $this->expectExceptionMessage('partial (filtered) indexes');
        (new MySqlSchemaGrammar())->compileIndexes($blueprint);
    }

    /**
     * An empty `where` predicate fails at the blueprint.
     */
    public function testPartialIndexEmptyPredicateThrows(): void
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('must be non-empty');
        (new Blueprint('users'))->index(null, ['user_id'], where: '   ');
    }

    /**
     * Both options compose on the supporting dialect.
     */
    public function testPartialIndexWithNullsNotDistinctPostgres(): void
    {
        $blueprint = (new Blueprint('invitations'))
            ->index(null, ['email'], unique: true, where: 'accepted_at IS NULL', nullsNotDistinct: true);
        $indexes = (new PostgresSchemaGrammar())->compileIndexes($blueprint);
        self::assertSame(
            ['CREATE UNIQUE INDEX "invitations_email_unique" ON "invitations" ("email") NULLS NOT DISTINCT WHERE accepted_at IS NULL'],
            $indexes,
        );
    }

    /**
     * A PLAIN (non-unique) index renders no NULLS clause — the semantics
     * only exist for unique indexes.
     */
    public function testPlainIndexHasNoNullsClause(): void
    {
        $blueprint = (new Blueprint('posts'))->column(ColumnType::BigInt, 'user_id', index: true);
        $indexes = (new PostgresSchemaGrammar())->compileIndexes($blueprint);
        self::assertSame(
            ['CREATE INDEX "posts_user_id_index" ON "posts" ("user_id")'],
            $indexes,
        );
    }

    // ---- CHECK constraints ----

    /**
     * A named CHECK constraint renders with its name VERBATIM (the same
     * rule as index(): the given name IS the whole final name), portably.
     */
    public function testNamedCheckConstraint(): void
    {
        $blueprint = (new Blueprint('products'))
            ->column(ColumnType::Float, 'price')
            ->check('price >= 0', 'price_positive');
        $sql = (new MySqlSchemaGrammar())->compileCreate($blueprint);
        self::assertSame(
            'CREATE TABLE `products` (`price` double NOT NULL, CONSTRAINT `price_positive` CHECK (price >= 0))',
            $sql,
        );
    }

    /**
     * An UNNAMED CHECK constraint derives its final name
     * (`{table}_{columns}_check` — same rule as indexes) so it is
     * diffable by name like every other constraint.
     */
    public function testUnnamedCheckConstraint(): void
    {
        $blueprint = (new Blueprint('products'))
            ->column(ColumnType::String, 'status', length: 20)
            ->check("status IN ('draft', 'published')");
        $sql = (new PostgresSchemaGrammar())->compileCreate($blueprint);
        self::assertSame(
            "CREATE TABLE \"products\" (\"status\" varchar(20) NOT NULL, CONSTRAINT \"products_status_check\" CHECK (status IN ('draft', 'published')))",
            $sql,
        );
    }

    /**
     * A CHECK constraint with an empty expression fails at the blueprint.
     */
    public function testEmptyCheckThrows(): void
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('non-empty expression');
        (new Blueprint('products'))->check('  ');
    }

    // ---- DEFERRABLE foreign keys ----

    /**
     * Postgres renders DEFERRABLE INITIALLY DEFERRED on a foreign key.
     */
    public function testDeferrableForeignKeyPostgres(): void
    {
        $blueprint = (new Blueprint('transfers'))
            ->column(ColumnType::BigInt, 'account_id')
            ->foreignKey(['account_id'], 'accounts', ['id'], deferrable: true, initiallyDeferred: true);
        $sql = (new PostgresSchemaGrammar())->compileCreate($blueprint);
        self::assertSame(
            'CREATE TABLE "transfers" ("account_id" bigint NOT NULL, '
            . 'FOREIGN KEY ("account_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY DEFERRED)',
            $sql,
        );
    }

    /**
     * MySQL refuses DEFERRABLE foreign keys — fail fast, not silently
     * immediate enforcement.
     */
    public function testDeferrableForeignKeyMySqlThrows(): void
    {
        $blueprint = (new Blueprint('transfers'))
            ->column(ColumnType::BigInt, 'account_id')
            ->foreignKey(['account_id'], 'accounts', ['id'], deferrable: true);
        $this->expectException(UnsupportedFeatureException::class);
        $this->expectExceptionMessage('DEFERRABLE foreign keys');
        (new MySqlSchemaGrammar())->compileCreate($blueprint);
    }

    /**
     * initiallyDeferred without deferrable fails at the blueprint —
     * INITIALLY DEFERRED implies DEFERRABLE in the SQL standard.
     */
    public function testInitiallyDeferredWithoutDeferrableThrows(): void
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('implies DEFERRABLE');
        (new Blueprint('transfers'))->foreignKey(['account_id'], 'accounts', ['id'], initiallyDeferred: true);
    }

    // ---- DROP INDEX ----

    /**
     * Each dialect compiles its own DROP INDEX syntax.
     */
    public function testCompileDropIndexPerDialect(): void
    {
        self::assertSame(
            'ALTER TABLE `users` DROP INDEX `users_email_unique`',
            (new MySqlSchemaGrammar())->compileDropIndex('users_email_unique', 'users'),
        );
        self::assertSame(
            'DROP INDEX "users_email_unique"',
            (new PostgresSchemaGrammar())->compileDropIndex('users_email_unique', 'users'),
        );
        self::assertSame(
            'DROP INDEX "users_email_unique"',
            (new SqliteSchemaGrammar())->compileDropIndex('users_email_unique', 'users'),
        );
    }

    /**
     * An Expression default is spliced verbatim.
     */
    public function testExpressionDefault(): void
    {
        $blueprint = (new Blueprint('posts'))
            ->column(ColumnType::DateTime, 'created_at', default: new Expression('CURRENT_TIMESTAMP'));
        $sql = (new PostgresSchemaGrammar())->compileCreate($blueprint);
        self::assertSame(
            'CREATE TABLE "posts" ("created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP)',
            $sql,
        );
    }

    /**
     * A composite foreign key compiles a table-level constraint.
     */
    public function testCompositeForeignKey(): void
    {
        $blueprint = (new Blueprint('tenant_users'))
            ->column(ColumnType::BigInt, 'tenant_id')
            ->column(ColumnType::BigInt, 'user_id')
            ->foreignKey(['tenant_id', 'user_id'], 'memberships', ['tenant_id', 'user_id'], onDelete: 'cascade');
        $sql = (new PostgresSchemaGrammar())->compileCreate($blueprint);
        self::assertSame(
            'CREATE TABLE "tenant_users" ("tenant_id" bigint NOT NULL, "user_id" bigint NOT NULL, '
            . 'FOREIGN KEY ("tenant_id", "user_id") REFERENCES "memberships" ("tenant_id", "user_id") ON DELETE CASCADE)',
            $sql,
        );
    }

    /**
     * A foreign key with mismatched arity fails fast.
     */
    public function testForeignKeyArityMismatchThrows(): void
    {
        $blueprint = (new Blueprint('tenant_users'))
            ->column(ColumnType::BigInt, 'tenant_id')
            ->column(ColumnType::BigInt, 'user_id');
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('matching arity');
        $blueprint->foreignKey(['tenant_id', 'user_id'], 'memberships', ['tenant_id']);
    }

    /**
     * getForeignKeys() unifies single-column and composite FKs.
     */
    public function testGetForeignKeysUnifiesSingleAndComposite(): void
    {
        $blueprint = (new Blueprint('team_members'))
            ->column(ColumnType::BigInt, 'team_id', foreign: 'teams.id')
            ->column(ColumnType::BigInt, 'user_id')
            ->foreignKey(['team_id', 'user_id'], 'memberships', ['team_id', 'user_id']);

        $foreignKeys = $blueprint->getForeignKeys();

        self::assertCount(2, $foreignKeys);
        self::assertSame(['team_id'], $foreignKeys[0]['columns']);
        self::assertSame(['teams', 'id'], $foreignKeys[0]['references']);
        self::assertSame(['team_id', 'user_id'], $foreignKeys[1]['columns']);
        self::assertSame(['memberships', 'team_id', 'user_id'], $foreignKeys[1]['references']);
    }

    /**
     * FK actions are validated at the boundary and stored as the enum —
     * a non-action string is rejected before it can reach the DDL.
     */
    public function testForeignKeyActionRejectsNonAction(): void
    {
        $blueprint = new Blueprint('users');

        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('A foreign key action must be one of CASCADE, SET NULL, RESTRICT, NO ACTION, or SET DEFAULT');
        $blueprint->foreignKey(['user_id'], 'users', ['id'], onDelete: 'cascade; DROP TABLE users');
    }

    /**
     * FK action strings normalize case-insensitively to the canonical enum.
     */
    public function testForeignKeyActionNormalizesCase(): void
    {
        $blueprint = (new Blueprint('users'))
            ->foreignKey(['user_id'], 'users', ['id'], onDelete: 'set null', onUpdate: 'No_Action');

        $foreignKeys = $blueprint->getForeignKeys();
        self::assertSame(ForeignKeyAction::SetNull, $foreignKeys[0]['onDelete']);
        self::assertSame(ForeignKeyAction::NoAction, $foreignKeys[0]['onUpdate']);
    }

    /**
     * A non-scalar, non-Expression default fails fast.
     */
    public function testInvalidDefaultThrows(): void
    {
        $blueprint = (new Blueprint('posts'))
            ->column(ColumnType::BigInt, 'count', default: [1, 2, 3]);
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('default must be a scalar');
        (new SqliteSchemaGrammar())->compileCreate($blueprint);
    }

    // ---- Alter ----

    /**
     * Adding a column compiles per dialect.
     */
    public function testAlterAddColumn(): void
    {
        $blueprint = (new Blueprint('users'))->string('nickname', 100);
        $sql = (new SqliteSchemaGrammar())->compileAddColumns($blueprint);
        self::assertSame('ALTER TABLE "users" ADD COLUMN "nickname" varchar(100) NOT NULL', $sql);
    }

    /**
     * Dropping a column works on MySQL and Postgres.
     */
    public function testAlterDropColumnMySql(): void
    {
        $blueprint = (new Blueprint('users'))->dropColumn('nickname');
        $sql = (new MySqlSchemaGrammar())->compileDropColumns($blueprint);
        self::assertSame('ALTER TABLE `users` DROP COLUMN `nickname`', $sql);
    }

    /**
     * Dropping a column works on Postgres.
     */
    public function testAlterDropColumnPostgres(): void
    {
        $blueprint = (new Blueprint('users'))->dropColumn('nickname');
        $sql = (new PostgresSchemaGrammar())->compileDropColumns($blueprint);
        self::assertSame('ALTER TABLE "users" DROP COLUMN "nickname"', $sql);
    }

    /**
     * SQLite cannot drop columns — it fails fast.
     */
    public function testAlterDropColumnSqliteThrows(): void
    {
        $blueprint = (new Blueprint('users'))->dropColumn('nickname');
        $this->expectException(UnsupportedFeatureException::class);
        $this->expectExceptionMessage('does not support dropping columns');
        (new SqliteSchemaGrammar())->compileDropColumns($blueprint);
    }

    // ---- Drop ----

    /**
     * Dropping a table compiles per dialect.
     */
    public function testDropTable(): void
    {
        self::assertSame(
            'DROP TABLE "users"',
            (new SqliteSchemaGrammar())->compileDrop('users'),
        );
        self::assertSame(
            'DROP TABLE `users`',
            (new MySqlSchemaGrammar())->compileDrop('users'),
        );
        self::assertSame(
            'DROP TABLE "users"',
            (new PostgresSchemaGrammar())->compileDrop('users'),
        );
    }

    // ---- Live SQLite round-trip ----

    /**
     * A table created via the connection's schema grammar can be queried.
     */
    public function testLiveSqliteCreateAndQuery(): void
    {
        $connection = new SqliteConnection(new \PDO('sqlite::memory:'));
        $connection->create($this->usersBlueprint());

        $connection->table('users')->insert([
            'name' => 'Alice',
            'email' => 'alice@example.com',
            'role_id' => 1,
        ]);

        $row = $connection->table('users')->where('email', '=', 'alice@example.com')->first();
        self::assertNotNull($row);
        self::assertSame('Alice', $row->name);
    }

    /**
     * An indexed column creates a real index on SQLite.
     */
    public function testLiveSqliteIndexCreated(): void
    {
        $connection = new SqliteConnection(new \PDO('sqlite::memory:'));
        $blueprint = (new Blueprint('posts'))
            ->id()
            ->column(ColumnType::BigInt, 'user_id', index: true);
        $connection->create($blueprint);

        $indexes = $connection->selectSql(
            "SELECT name FROM sqlite_master WHERE type = 'index' AND tbl_name = 'posts'",
        );
        $indexRow = $indexes->first();
        self::assertNotNull($indexRow);
        self::assertSame('posts_user_id_index', $indexRow->name);
    }

    /**
     * Dropping a table via the connection removes it.
     */
    public function testLiveSqliteDrop(): void
    {
        $connection = new SqliteConnection(new \PDO('sqlite::memory:'));
        $connection->create($this->usersBlueprint());
        $connection->drop('users');

        $this->expectException(\BlueprintAU\Radiant\Database\Exceptions\QueryException::class);
        // The message is log-safe by contract — it never embeds the SQL.
        $this->expectExceptionMessage('SQL error executing query');
        $connection->table('users')->get();
    }
}