<?php

declare(strict_types=1);

namespace BlueprintAU\Radiant\Tests\Unit\Schema;

use BlueprintAU\Radiant\Database\Connections\SqliteConnection;
use BlueprintAU\Radiant\Database\Exceptions\UnsupportedFeatureException;
use BlueprintAU\Radiant\Database\Query\Expression;
use BlueprintAU\Radiant\Database\Schema\Blueprint;
use BlueprintAU\Radiant\Database\Schema\Enums\ColumnType;
use BlueprintAU\Radiant\Database\Schema\Enums\ForeignKeyAction;
use BlueprintAU\Radiant\Database\Schema\Grammars\MySqlSchemaGrammar;
use BlueprintAU\Radiant\Database\Schema\Grammars\PostgresSchemaGrammar;
use BlueprintAU\Radiant\Database\Schema\Enums\SchemaOperation;
use BlueprintAU\Radiant\Database\Schema\Grammars\SqliteSchemaGrammar;
use PHPUnit\Framework\TestCase;

/**
 * Compile-only tests for the schema grammar chain, plus a live SQLite
 * round-trip.
 */
final class SchemaGrammarTest extends TestCase
{
    /**
     * A blueprint with a typical users table.
     *
     * @return Blueprint The blueprint.
     */
    private function usersBlueprint(): Blueprint
    {
        return (new Blueprint('users'))
            ->id()
            ->string('name', 255)
            ->column(ColumnType::String, 'email', length: 255, unique: true)
            ->timestamp('email_verified_at')
            ->foreignId('role_id', 'roles.id', onDelete: 'cascade');
    }

    // ---- Create ----

    /**
     * SQLite compiles a CREATE TABLE with quoted identifiers.
     */
    public function testCreateSqlite(): void
    {
        $sql = (new SqliteSchemaGrammar())->compileCreate($this->usersBlueprint());
        self::assertSame(
            'CREATE TABLE "users" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, '
            . '"name" varchar(255) NOT NULL, "email" varchar(255) NOT NULL UNIQUE, '
            . '"email_verified_at" datetime, "role_id" integer NOT NULL, '
            . 'FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON DELETE CASCADE)',
            $sql,
        );
    }

    /**
     * MySQL compiles a CREATE TABLE with backtick quoting and AUTO_INCREMENT.
     */
    public function testCreateMySql(): void
    {
        $sql = (new MySqlSchemaGrammar())->compileCreate($this->usersBlueprint());
        self::assertSame(
            'CREATE TABLE `users` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, '
            . '`name` varchar(255) NOT NULL, `email` varchar(255) NOT NULL UNIQUE, '
            . '`email_verified_at` datetime, `role_id` bigint NOT NULL, '
            . 'FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE)',
            $sql,
        );
    }

    /**
     * Postgres compiles a CREATE TABLE with double-quote quoting and an
     * identity column.
     */
    public function testCreatePostgres(): void
    {
        $sql = (new PostgresSchemaGrammar())->compileCreate($this->usersBlueprint());
        self::assertSame(
            'CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, '
            . '"name" varchar(255) NOT NULL, "email" varchar(255) NOT NULL UNIQUE, '
            . '"email_verified_at" timestamp, "role_id" bigint NOT NULL, '
            . 'FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON DELETE CASCADE)',
            $sql,
        );
    }

    /**
     * A composite primary key is declared table-level.
     */
    public function testCompositePrimaryKey(): void
    {
        $blueprint = (new Blueprint('user_roles'))
            ->column(ColumnType::BigInt, 'user_id', primaryKey: true)
            ->column(ColumnType::BigInt, 'role_id', primaryKey: true);
        $sql = (new SqliteSchemaGrammar())->compileCreate($blueprint);
        self::assertSame(
            'CREATE TABLE "user_roles" ("user_id" integer NOT NULL, "role_id" integer NOT NULL, '
            . 'PRIMARY KEY ("user_id", "role_id"))',
            $sql,
        );
    }

    /**
     * A default value is quoted as a literal.
     */
    public function testDefaultValue(): void
    {
        $blueprint = (new Blueprint('settings'))->column(ColumnType::Boolean, 'active', default: true);
        $sql = (new SqliteSchemaGrammar())->compileCreate($blueprint);
        self::assertSame(
            'CREATE TABLE "settings" ("active" tinyint(1) NOT NULL DEFAULT 1)',
            $sql,
        );
    }

    /**
     * Creating a table with no columns fails fast.
     */
    public function testCreateNoColumnsThrows(): void
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('no columns');
        (new SqliteSchemaGrammar())->compileCreate(new Blueprint('users'));
    }

    /**
     * A string column requires a length — fail-fast rather than a silent
     * default.
     */
    public function testStringRequiresLength(): void
    {
        // Use the low-level column() so a missing length reaches the
        // runtime validation (string() now requires the length at
        // compile-time).
        $blueprint = (new Blueprint('users'))->column(ColumnType::String, 'name');
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('requires a length');
        (new SqliteSchemaGrammar())->compileCreate($blueprint);
    }

    /**
     * A foreign key with a non-bigint type renders that type.
     */
    public function testForeignIdWithExplicitType(): void
    {
        $blueprint = (new Blueprint('posts'))
            ->id()
            ->foreignId('user_uuid', 'users.uuid', ColumnType::String, length: 36);
        $sql = (new MySqlSchemaGrammar())->compileCreate($blueprint);
        self::assertSame(
            'CREATE TABLE `posts` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, '
            . '`user_uuid` varchar(36) NOT NULL, '
            . 'FOREIGN KEY (`user_uuid`) REFERENCES `users` (`uuid`))',
            $sql,
        );
    }

    /**
     * An indexed column compiles a portable CREATE INDEX statement.
     */
    public function testIndexCompilesCreateIndex(): void
    {
        $blueprint = (new Blueprint('posts'))->column(ColumnType::BigInt, 'user_id', index: true);
        $indexes = (new SqliteSchemaGrammar())->compileIndexes($blueprint);
        self::assertSame(
            ['CREATE INDEX "posts_user_id_index" ON "posts" ("user_id")'],
            $indexes,
        );
    }

    /**
     * A unique column is not duplicated as a plain index (already inline).
     */
    public function testUniqueColumnNotIndexedSeparately(): void
    {
        $blueprint = (new Blueprint('users'))->column(ColumnType::String, 'email', length: 255, unique: true, index: true);
        $indexes = (new MySqlSchemaGrammar())->compileIndexes($blueprint);
        self::assertSame([], $indexes);
    }

    /**
     * A blueprint with no indexed columns compiles no index statements.
     */
    public function testNoIndexesWhenNoneDeclared(): void
    {
        $indexes = (new SqliteSchemaGrammar())->compileIndexes($this->usersBlueprint());
        self::assertSame([], $indexes);
    }

    /**
     * A composite index compiles a multi-column CREATE INDEX.
     */
    public function testCompositeIndex(): void
    {
        // An explicit name IS the whole name — rendered verbatim.
        $blueprint = (new Blueprint('memberships'))
            ->index('team_role', ['team_id', 'role_id']);
        $indexes = (new SqliteSchemaGrammar())->compileIndexes($blueprint);
        self::assertSame(
            ['CREATE INDEX "team_role" ON "memberships" ("team_id", "role_id")'],
            $indexes,
        );
    }

    /**
     * A single-column index() with a custom name compiles.
     */
    public function testSingleColumnIndex(): void
    {
        $blueprint = (new Blueprint('users'))
            ->index('active', ['is_active']);
        $indexes = (new MySqlSchemaGrammar())->compileIndexes($blueprint);
        self::assertSame(
            ['CREATE INDEX `active` ON `users` (`is_active`)'],
            $indexes,
        );
    }

    /**
     * A unique composite index compiles CREATE UNIQUE INDEX.
     */
    public function testUniqueCompositeIndex(): void
    {
        $blueprint = (new Blueprint('memberships'))
            ->index('team_user', ['team_id', 'user_id'], unique: true);
        $indexes = (new MySqlSchemaGrammar())->compileIndexes($blueprint);
        self::assertSame(
            ['CREATE UNIQUE INDEX `team_user` ON `memberships` (`team_id`, `user_id`)'],
            $indexes,
        );
    }

    /**
     * An index requires at least one column.
     */
    public function testIndexRequiresColumns(): void
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('at least one column');
        (new Blueprint('users'))->index('empty', []);
    }

    /**
     * An Expression default is spliced verbatim.
     */
    public function testExpressionDefault(): void
    {
        $blueprint = (new Blueprint('posts'))
            ->column(ColumnType::DateTime, 'created_at', default: new Expression('CURRENT_TIMESTAMP'));
        $sql = (new PostgresSchemaGrammar())->compileCreate($blueprint);
        self::assertSame(
            'CREATE TABLE "posts" ("created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP)',
            $sql,
        );
    }

    /**
     * A composite foreign key compiles a table-level constraint.
     */
    public function testCompositeForeignKey(): void
    {
        $blueprint = (new Blueprint('tenant_users'))
            ->column(ColumnType::BigInt, 'tenant_id')
            ->column(ColumnType::BigInt, 'user_id')
            ->foreignKey(['tenant_id', 'user_id'], 'memberships', ['tenant_id', 'user_id'], onDelete: 'cascade');
        $sql = (new PostgresSchemaGrammar())->compileCreate($blueprint);
        self::assertSame(
            'CREATE TABLE "tenant_users" ("tenant_id" bigint NOT NULL, "user_id" bigint NOT NULL, '
            . 'FOREIGN KEY ("tenant_id", "user_id") REFERENCES "memberships" ("tenant_id", "user_id") ON DELETE CASCADE)',
            $sql,
        );
    }

    /**
     * A foreign key with mismatched arity fails fast.
     */
    public function testForeignKeyArityMismatchThrows(): void
    {
        $blueprint = (new Blueprint('tenant_users'))
            ->column(ColumnType::BigInt, 'tenant_id')
            ->column(ColumnType::BigInt, 'user_id');
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('matching arity');
        $blueprint->foreignKey(['tenant_id', 'user_id'], 'memberships', ['tenant_id']);
    }

    /**
     * getForeignKeys() unifies single-column and composite FKs.
     */
    public function testGetForeignKeysUnifiesSingleAndComposite(): void
    {
        $blueprint = (new Blueprint('team_members'))
            ->column(ColumnType::BigInt, 'team_id', foreign: 'teams.id')
            ->column(ColumnType::BigInt, 'user_id')
            ->foreignKey(['team_id', 'user_id'], 'memberships', ['team_id', 'user_id']);

        $foreignKeys = $blueprint->getForeignKeys();

        self::assertCount(2, $foreignKeys);
        self::assertSame(['team_id'], $foreignKeys[0]['columns']);
        self::assertSame(['teams', 'id'], $foreignKeys[0]['references']);
        self::assertSame(['team_id', 'user_id'], $foreignKeys[1]['columns']);
        self::assertSame(['memberships', 'team_id', 'user_id'], $foreignKeys[1]['references']);
    }

    /**
     * FK actions are validated at the boundary and stored as the enum —
     * a non-action string is rejected before it can reach the DDL.
     */
    public function testForeignKeyActionRejectsNonAction(): void
    {
        $blueprint = new Blueprint('users');

        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('A foreign key action must be one of CASCADE, SET NULL, RESTRICT, NO ACTION, or SET DEFAULT');
        $blueprint->foreignKey(['user_id'], 'users', ['id'], onDelete: 'cascade; DROP TABLE users');
    }

    /**
     * FK action strings normalize case-insensitively to the canonical enum.
     */
    public function testForeignKeyActionNormalizesCase(): void
    {
        $blueprint = (new Blueprint('users'))
            ->foreignKey(['user_id'], 'users', ['id'], onDelete: 'set null', onUpdate: 'No_Action');

        $foreignKeys = $blueprint->getForeignKeys();
        self::assertSame(ForeignKeyAction::SetNull, $foreignKeys[0]['onDelete']);
        self::assertSame(ForeignKeyAction::NoAction, $foreignKeys[0]['onUpdate']);
    }

    /**
     * A non-scalar, non-Expression default fails fast.
     */
    public function testInvalidDefaultThrows(): void
    {
        $blueprint = (new Blueprint('posts'))
            ->column(ColumnType::BigInt, 'count', default: [1, 2, 3]);
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('default must be a scalar');
        (new SqliteSchemaGrammar())->compileCreate($blueprint);
    }

    // ---- Alter ----

    /**
     * Adding a column compiles per dialect.
     */
    public function testAlterAddColumn(): void
    {
        $blueprint = (new Blueprint('users'))->string('nickname', 100);
        $sql = (new SqliteSchemaGrammar())->compileAlter(SchemaOperation::AddColumn, $blueprint);
        self::assertSame('ALTER TABLE "users" ADD COLUMN "nickname" varchar(100) NOT NULL', $sql);
    }

    /**
     * Dropping a column works on MySQL and Postgres.
     */
    public function testAlterDropColumnMySql(): void
    {
        $blueprint = (new Blueprint('users'))->dropColumn('nickname');
        $sql = (new MySqlSchemaGrammar())->compileAlter(SchemaOperation::DropColumn, $blueprint);
        self::assertSame('ALTER TABLE `users` DROP COLUMN `nickname`', $sql);
    }

    /**
     * Dropping a column works on Postgres.
     */
    public function testAlterDropColumnPostgres(): void
    {
        $blueprint = (new Blueprint('users'))->dropColumn('nickname');
        $sql = (new PostgresSchemaGrammar())->compileAlter(SchemaOperation::DropColumn, $blueprint);
        self::assertSame('ALTER TABLE "users" DROP COLUMN "nickname"', $sql);
    }

    /**
     * SQLite cannot drop columns — it fails fast.
     */
    public function testAlterDropColumnSqliteThrows(): void
    {
        $blueprint = (new Blueprint('users'))->dropColumn('nickname');
        $this->expectException(UnsupportedFeatureException::class);
        $this->expectExceptionMessage('does not support dropping columns');
        (new SqliteSchemaGrammar())->compileAlter(SchemaOperation::DropColumn, $blueprint);
    }

    // ---- Drop ----

    /**
     * Dropping a table compiles per dialect.
     */
    public function testDropTable(): void
    {
        self::assertSame(
            'DROP TABLE "users"',
            (new SqliteSchemaGrammar())->compileDrop('users'),
        );
        self::assertSame(
            'DROP TABLE `users`',
            (new MySqlSchemaGrammar())->compileDrop('users'),
        );
        self::assertSame(
            'DROP TABLE "users"',
            (new PostgresSchemaGrammar())->compileDrop('users'),
        );
    }

    // ---- Live SQLite round-trip ----

    /**
     * A table created via the connection's schema grammar can be queried.
     */
    public function testLiveSqliteCreateAndQuery(): void
    {
        $connection = new SqliteConnection(new \PDO('sqlite::memory:'));
        $connection->create($this->usersBlueprint());

        $connection->table('users')->insert([
            'name' => 'Alice',
            'email' => 'alice@example.com',
            'role_id' => 1,
        ]);

        $row = $connection->table('users')->where('email', '=', 'alice@example.com')->first();
        self::assertNotNull($row);
        self::assertSame('Alice', $row->name);
    }

    /**
     * An indexed column creates a real index on SQLite.
     */
    public function testLiveSqliteIndexCreated(): void
    {
        $connection = new SqliteConnection(new \PDO('sqlite::memory:'));
        $blueprint = (new Blueprint('posts'))
            ->id()
            ->column(ColumnType::BigInt, 'user_id', index: true);
        $connection->create($blueprint);

        $indexes = $connection->selectSql(
            "SELECT name FROM sqlite_master WHERE type = 'index' AND tbl_name = 'posts'",
        );
        self::assertSame('posts_user_id_index', $indexes->first()->name);
    }

    /**
     * Dropping a table via the connection removes it.
     */
    public function testLiveSqliteDrop(): void
    {
        $connection = new SqliteConnection(new \PDO('sqlite::memory:'));
        $connection->create($this->usersBlueprint());
        $connection->drop('users');

        $this->expectException(\BlueprintAU\Radiant\Database\Exceptions\QueryException::class);
        $this->expectExceptionMessage('SQLSTATE error executing query');
        $connection->table('users')->get();
    }
}